In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# replace None with an integer n to print n rows
pd.set_option('display.max_rows', None)

In [2]:
# function to get T, G, M values: (starname, dataframe)

def TGM_finder(name, dataframe):
    row = dataframe.loc[dataframe['Star'] == name]
    # return T, G, M
    return row.values[0][1], row.values[0][2], row.values[0][3]

In [3]:
# Read the HARPS-GTO csv files into dataframes

SwoP = pd.read_csv("starswithoutplanet.csv")      # Stars WithOut planets
SwP = pd.read_csv("starswithplanet.csv")          # Stars With Planets

### <font color=steelblue> Insights on the original .csv files </font>

* **SwP has 220 entries- 147 unique host stars and 220 unique planets.**

> 1. The name of planets are always "hostname x" where x = b, c, d, etc. (refer columns 'hostname_1' and 'pl_name'; Exception- rows 140 & 168). 'Star---' column is redundant wrt 'hostname_1'.
> 2. 'TeffK' is same as 'TeffK'. But 'TeffK_x' and 'Teff_y' are different.
> 3. 'logg[cm/s2]', 'logg[cm/s2]_x' and, 'logg[cm/s2]_y' are all different.

* **SwoP has 947 unique planetless stars:**

### <font color=steelblue> In the following code, we consider:</font>
> 1. star ('hostname_1') 
> 2. temperature ('TeffK') 
> 3. metallicity [Fe/H] ('[Fe/H]---_x')
> 4. gravity ('logg[cm/s2]').

## *Derive dataframes with relevant columns from the original dataframes:*

In [4]:
# step 1: make a copy of parameter columns
cSwP = SwP[['hostname_1','TeffK', 'logg[cm/s2]', '[Fe/H]---_x']].copy()
cSwoP = SwoP[['Star---','TeffK', 'logg[cm/s2]', '[Fe/H]---_x']].copy()

# rename the 'Star---' column for convenience
cSwP = cSwP.rename(columns={'hostname_1': 'Star'}).copy()
cSwoP = cSwoP.rename(columns={'Star---': 'Star'}).copy()

# drop duplicates in nSwP: original nSwP has 220 entries but only 147 unique stars
cSwP = cSwP.drop_duplicates().copy()
cSwP = cSwP.reset_index(drop=True).copy()

## *Rank the nearest neighbours*

In [5]:
# set the cutoff radius for temperature
radius = 160

In [6]:
def ranker(star_wp):
        # copy the row from cSwP in consideration
        tdf1 = cSwP.loc[cSwP['Star'] == star_wp]

        # extract the T, G, M for the star_wp
        T, G, M = TGM_finder(star_wp, cSwP)

        # get stars in cSwoP within radius of star_wp
        tdf2 = cSwoP.loc[np.abs(cSwoP['TeffK']-T)<=radius]

        # merge tdf1 and tdf2 rowwise such that first row shows the star_wp
        tdf3 = pd.concat([tdf1, tdf2], ignore_index = True)

        # add columns to tdf3 showing difference between a star's TGM values and star_wp's TGM values

        tdf3[u'ΔT'] = (tdf3['TeffK']-T).abs()
        tdf3[u'ΔG'] = (tdf3['logg[cm/s2]']-G).abs()
        tdf3[u'ΔM'] = (tdf3['[Fe/H]---_x']-M).abs()

        # add columns to tdf3 with ranking of each parameter
        for key, col in [[u'ΔT','T_rank'], [u'ΔG','G_rank'], [u'ΔM', 'M_rank']]:
            x = np.zeros(len(tdf3[key]))
            x[tdf3[key].argsort()]=np.arange(len(tdf3[key]))
            tdf3[col] = x

        # add a mean ranking column for each star (note that star_wp will have rank 0)
        tdf3['mean_rank'] = (tdf3.T_rank+ tdf3.G_rank+tdf3.M_rank)/3.

        # extract only relevant columns from tdf3 as result1
        result1 = tdf3.sort_values('mean_rank').reset_index(drop=True)

        # sort result1 based on ranking
        result1 = result1[['Star','TeffK', 'logg[cm/s2]', '[Fe/H]---_x']]
        
        return tdf3, result1
    
# tdf3 stores calculations based on continuous parameters and result1 stores only relevant columns

# <font color=midnightblue> OUTPUT SECTION </font>
***
**This is the list of stars with planets from HARPS- GTO data**

In [7]:
cSwP

            Star  TeffK  logg[cm/s2]  [Fe/H]---_x
0     BD-08 2823   4816         4.43        -0.06
1       BD-17 63   4665         4.19         0.01
2      HD 100777   5536         4.33         0.25
3       HD 10180   5911         4.39         0.08
4      HD 101930   5164         4.40         0.13
5      HD 102117   5657         4.31         0.28
6      HD 102365   5629         4.44        -0.29
7      HD 102843   5432         4.35         0.16
8      HD 103197   5250         4.45         0.22
9      HD 103720   5017         4.43        -0.02
10     HD 103949   4881         4.48        -0.07
11     HD 104067   4969         4.47        -0.06
12      HD 10647   6218         4.62         0.00
13       tau Cet   5310         4.44        -0.52
14     HD 107148   5805         4.40         0.31
15     HD 108147   6260         4.47         0.18
16     HD 108341   5122         4.45         0.04
17     HD 109271   5783         4.28         0.10
18     HD 111232   5460         4.43        -0.43
19     HD 114386   4910         4.39        -0.07
20     HD 114613   5729         3.97         0.19
21     HD 114729   5844         4.19        -0.28
22     HD 114783   5133         4.42         0.03
23        61 Vir   5558         4.36        -0.02
24     HD 117207   5667         4.32         0.22
25     HD 117618   5990         4.41         0.03
26      HD 11964   5332         3.90         0.08
27     HD 121504   6022         4.49         0.14
28       GJ 3021   5514         4.50         0.07
29     HD 125595   4691         4.17         0.08
30     HD 125612   5913         4.43         0.24
31     HD 126525   5638         4.37        -0.10
32     HD 130322   5365         4.37        -0.02
33     HD 131664   5901         4.50         0.31
34     HD 134060   5966         4.43         0.14
35     HD 134987   5740         4.30         0.25
36     HD 136352   5664         4.39        -0.34
37     HD 137388   5240         4.42         0.18
38      HD 13808   5087         4.40        -0.20
39     HD 141937   5893         4.45         0.13
40        HD 142   6403         4.62         0.09
41   HD 142022 A   5508         4.35         0.19
42     HD 145377   6054         4.53         0.12
43       HD 1461   5765         4.38         0.19
44     HD 147513   5858         4.50         0.03
45     HD 148156   6251         4.51         0.25
46      HD 15337   5179         4.39         0.06
47     HD 153950   6074         4.39        -0.01
48     HD 156411   5910         3.99        -0.11
49     HD 159868   5558         3.96        -0.08
50     HD 160691   5780         4.27         0.30
51      HD 16141   5806         4.19         0.16
52     HD 162020   4861         4.48        -0.10
53      HD 16417   5841         4.16         0.13
54     HD 166724   5127         4.43        -0.09
55     HD 168746   5568         4.33        -0.10
56     HD 169830   6361         4.21         0.18
57        HR 810   6227         4.53         0.19
58     HD 171028   5671         3.84        -0.48
59     HD 175607   5392         4.51        -0.62
60     HD 176986   5018         4.45         0.00
61     HD 177565   5627         4.39         0.08
62     HD 179949   6287         4.54         0.21
63     HD 181433   4962         4.37         0.33
64     HD 181720   5792         4.25        -0.53
65     HD 190647   5639         4.18         0.23
66     HD 190984   6007         4.02        -0.49
67     HD 192310   5166         4.51        -0.04
68     HD 196050   5917         4.32         0.23
69      HD 19994   6289         4.48         0.24
70      HD 20003   5494         4.41         0.04
71     HD 202206   5757         4.47         0.29
72     HD 204313   5776         4.38         0.18
73     HD 204941   5056         4.48        -0.19
74      HD 20781   5256         4.37        -0.11
75      HD 20782   5774         4.37        -0.06
76     HD 207832   5718         4.45         0.15
77      HD 20794   5401         4.40        -0.40
78     HD 208487   6146         4.48         0.08
79      HD 20868   4802         4.26         0.05
80     eps Ind A   4754         4.45        -0.20
81     HD 209458   6118         4.50         0.03
82     HD 210277   5505         4.30         0.18
83     HD 212301   6271         4.55         0.18
84     HD 213240   5982         4.27         0.14
85      HD 21411   5473         4.51        -0.26
86     HD 215152   4935         4.40        -0.10
87     HD 215497   5110         4.40         0.20
88     HD 216435   6008         4.20         0.24
89     HD 216770   5424         4.38         0.24
90      HD 21693   5430         4.37         0.00
91        GJ 143   4723         4.40        -0.02
92     HD 217786   5966         4.35        -0.14
93     HD 219077   5362         4.00        -0.13
94       eps Eri   5153         4.53        -0.11
95     HD 221287   6374         4.62         0.04
96     HD 221420   5847         4.03         0.33
97     HD 222582   5779         4.37        -0.01
98      HD 23079   5980         4.48        -0.12
99      HD 23472   4813         4.38        -0.19
100     HD 24085   6065         4.47         0.17
101     HD 25171   6160         4.43        -0.11
102      HD 2638   5198         4.43         0.12
103     HD 26965   5153         4.39        -0.31
104     HD 27894   4952         4.39         0.20
105     HD 28185   5667         4.42         0.21
106     HD 28254   5653         4.15         0.36
107    HD 290327   5505         4.41        -0.14
108     HD 30177   5601         4.34         0.37
109     HD 30669   5400         4.37         0.13
110     HD 31527   5898         4.45        -0.17
111    HD 330075   5025         4.32         0.03
112     HD 39091   6003         4.42         0.09
113     HD 40307   4977         4.47        -0.31
114      HD 4208   5599         4.44        -0.28
115      HD 4308   5644         4.38        -0.34
116     HD 43197   5449         4.30         0.36
117     HD 44219   5766         4.20         0.04
118     HD 45184   5869         4.47         0.04
119     HD 45364   5434         4.38        -0.17
120     HD 47186   5675         4.36         0.23
121     HD 51608   5358         4.36        -0.07
122     HD 52265   6136         4.36         0.21
123       HD 564   5902         4.53        -0.20
124     HD 63454   4840         4.30         0.06
125     HD 63765   5432         4.42        -0.16
126     HD 65216   5612         4.44        -0.17
127     HD 66428   5705         4.31         0.25
128      HD 6718   5723         4.44        -0.07
129     HD 69830   5402         4.40        -0.06
130     HD 70642   5668         4.40         0.18
131      HD 7199   5386         4.34         0.28
132     HD 72659   5926         4.24        -0.02
133     HD 73267   5373         4.37         0.05
134      HD 7449   6024         4.51        -0.11
135     HD 75289   6161         4.37         0.30
136     HD 82943   5989         4.43         0.26
137      HD 8326   4971         4.48         0.02
138     HD 83443   5511         4.43         0.34
139      HD 8535   6158         4.42         0.04
140     HD 85390   5186         4.41        -0.07
141     HD 85512   4715         4.39        -0.32
142     HD 90156   5599         4.48        -0.24
143     HD 92788   5744         4.39         0.27
144     HD 93083   5105         4.43         0.09
145      TOI-431   4891         4.41         0.02
146     HIP 5158   4813         4.32         0.17

**Enter the row number (0-146) of any star from the above list to find similar stars without planets:**

In [8]:
rollno = int(input())
full_calculation, result = ranker(cSwP['Star'][rollno])

1

**The first row is the star you chose. The rest are its neighbours printed in descending degree of similarity.**

In [9]:
result

          Star  TeffK  logg[cm/s2]  [Fe/H]---_x
0     BD-17 63   4665         4.19         0.01
1     HIP21934   4674         4.19         0.03
2      HD11938   4703         4.25         0.01
3      HD45977   4689         4.30         0.03
4    BD-064196   4688         4.30        -0.03
5    BD-034797   4622         4.21         0.06
6    HIP116374   4626         4.31         0.01
7     HD108935   4724         4.30         0.02
8     HIP67126   4681         4.20        -0.19
9     HD297396   4717         4.30         0.06
10    HD119291   4611         4.22        -0.10
11    HD191902   4691         4.25        -0.18
12     HD36003   4647         4.31        -0.20
13    HD189987   4746         4.25        -0.06
14   BD-090872   4660         4.35        -0.19
15    HIP17346   4699         4.32        -0.16
16    HIP57688   4712         4.32        -0.14
17     HD20492   4770         4.30         0.02
18    HIP36347   4719         4.38        -0.05
19    HD132411   4673         4.32        -0.29
20    HD117938   4738         4.27        -0.13
21    HD170493   4751         4.24         0.14
22   HIP102025   4684         4.32        -0.28
23    HD199933   4730         4.32        -0.15
24    HD109368   4651         4.36        -0.23
25     HD52919   4698         4.37        -0.17
26     HD13789   4740         4.33        -0.06
27    HD21209A   4671         4.31        -0.41
28    HD183783   4595         4.29        -0.20
29     HD29985   4678         4.39        -0.22
30   BD-223528   4747         4.28        -0.17
31     HIP7743   4692         4.39        -0.17
32     HD31560   4751         4.33        -0.07
33   BD-213153   4622         4.38        -0.17
34   BD-044138   4604         4.39        -0.11
35    HD176535   4727         4.36        -0.15
36    HD326267   4719         4.31        -0.26
37   HIP113596   4580         4.25        -0.21
38    HD218511   4556         4.31        -0.10
39   BD-120327   4680         4.35        -0.34
40    HD192961   4624         4.31        -0.35
41    HD215722   4728         4.40        -0.10
42    HD101650   4626         4.29        -0.45
43    HIP18918   4572         4.28        -0.20
44    HD211583   4761         4.39         0.05
45    HD151692   4737         4.40        -0.07
46    HD105671   4748         4.42        -0.02
47     HD30523   4662         4.57        -0.16
48   BD-140184   4714         4.32        -0.38
49    HD116963   4735         4.43        -0.06
50    HD188559   4786         4.33        -0.11
51     HD58489   4800         4.33         0.10
52   BD-130321   4772         4.41         0.02
53     HD93380   4649         4.35        -0.72
54   BD-053176   4758         4.39        -0.09
55    HD203413   4812         4.39         0.01
56     HD16270   4786         4.39         0.06
57   BD-130116   4615         4.33        -0.49
58    HD191285   4634         4.41        -0.28
59   BD-053596   4594         4.32        -0.34
60   BD-010184   4728         4.34        -0.34
61   BD-050484   4674         4.42        -0.39
62    HIP38324   4615         4.39        -0.30
63    HD152533   4822         4.36        -0.04
64     HD73583   4695         4.50        -0.21
65     HD96673   4788         4.38        -0.13
66    HD125271   4779         4.33        -0.22
67     HD42505   4738         4.40        -0.22
68   BD-064756   4646         4.54        -0.23
69    HD126829   4726         4.51        -0.14
70   HIP103867   4559         4.14        -0.45
71     HD16280   4754         4.39        -0.19
72    HD120491   4680         4.49        -0.34
73    HD202819   4737         4.40        -0.26
74   BD-173242   4627         4.48        -0.29
75   BD-145003   4640         4.41        -0.51
76    HD219495   4787         4.40         0.13
77   BD-063481   4815         4.36        -0.14
78    HIP21539   4578         4.33        -0.33
79    HIP59925   4590         4.40        -0.26
80      HD4838   4704         4.63        -0.21
81   BD-012505   4741         4.51        -0.11
82    HD187760   4618         4.45        -0.32
83    HD202389   4732         4.43        -0.25
84     HIP7058   4749         4.55        -0.10
85     HD14635   4806         4.45        -0.03
86    HD154387   4719         4.50        -0.25
87    HD168159   4783         4.42        -0.15
88    HIP22059   4741         4.40        -0.32
89    HD210975   4749         4.37        -0.43
90        HD55   4679         4.51        -0.66
91   BD-092670   4806         4.46        -0.08
92    HIP45301   4788         4.46        -0.12
93    HIP25612   4571         4.35        -0.50
94     HD89668   4811         4.45        -0.11
95    HD142709   4728         4.44        -0.35
96    HD154363   4723         4.41        -0.62
97   BD-195953   4775         4.51        -0.14
98   HIP109421   4576         4.42        -0.27
99    HD222237   4780         4.37        -0.38
100   HD193406   4728         4.50        -0.34
101   HD137010   4797         4.41        -0.22
102   HD160836   4791         4.49        -0.16
103   HD309701   4814         4.39        -0.30
104   HIP54597   4799         4.43        -0.22
105    HIP9398   4734         4.49        -0.43
106  HIP102964   4797         4.43        -0.23
107   HIP39470   4571         4.40        -0.39
108   HD101581   4738         4.46        -0.52
109  BD-091261   4717         4.69        -0.75
110    HD65277   4802         4.43        -0.31
111  BD-094191   4804         4.44        -0.32
112   HIP26542   4750         4.48        -0.54
113   HD137303   4756         4.51        -0.35
114  BD-033746   4732         4.63        -0.90
115    HD82342   4820         4.41        -0.54
116   HD218572   4785         4.54        -0.56
117    HD57568   4821         4.51        -0.47
118   HIP80083   4800         4.78        -0.80
119  BD-123458   4803         4.86        -0.83
120   HD108564   4818         4.67        -0.97